### ISSUE TITLE
"integer :: i" replaced by "integer:: i"?

### ISSUE THREAD

**Issue by zaikunzhang** [rudrab/vimf90#10]
Thank you for developing vimf90.

With this plugin, when executing ":w", I note that all declarations like "integer :: i" are replaced by "integer:: i" (the space before :: is removed). The same thing happens for other declarations with "::", but not those with ":" (e.g., only : a). 

Is this intended? If yes, why "integer:: i" is considered better than "integer :: i"? Thank you!

**Comment by rudrab** [comment]
Hi, thanks for letting me know about them. 
However, please let me know the following:
1. Have you installed the plugins it asked for?
2.  what is your vimf90 settings in .vimrc.

Thanks.

**Comment by zaikunzhang** [comment]
Hello @rudrab ! Thank you for your quick response. 

1. Below you will find a minimal vimrc to reproduce the behavior. My Vim fulfills the first point in section "Dependencies" here: https://github.com/rudrab/vimf90 , i.e., Vim8.1 + python3. I  also attach a Fortran code for you to try. The Fortran code is not minimal (I do not think it needs to be) --- I just copied a piece of code I am working on. 

2. Looking into the code of vimf90, I find that the behavior is due to line 65 of ftplugin/fortran_state.vim, namely 
  au BufWritePre <buffer> silent! :%s/\v(\w|\)) ?(\:\:) ?(\w|-)/\1\2 \3/g     " `::`

3. If my understanding is correct, lines 60--67  of fortran_state.vim are automatically triming the Fortran code before writing. This is a great idea! I note that the cursor position is not preserved in such a process. For example, suppose that we are editing the Fortran code below, and the cursor is currently in line 1. Now we execute ":w". Then the cursor will jump to line 64 --- it is where the last change is made by fortran_state.vim. I guess this jump may be a bit surprising to most users. For your reference, see https://stackoverflow.com/questions/7894330/preserve-last-editing-position-in-vim and https://vi.stackexchange.com/questions/7761/how-to-restore-the-position-of-the-cursor-after-executing-a-normal-command. 

Again, thank you very much for this great plugin! 

"""""""""""""""""""""""""""""""""Minimal vimrc"""""""""""""""""""""""""""""""""""""
set nocompatible
set showmatch
set showcmd
set number
set numberwidth=1

filetype plugin on

" Automatic installation of vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '. data_dir . '/autoload/plug.vim --create-dirs ' .
      \ 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'rudrab/vimf90' 
call plug#end()
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Example of Fortran Code !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! This is an example to illustrate the usage of NEWUOA.
!
! Coded by Zaikun Zhang in July 2020 based on Powell's Fortran 77 code.


!!!!!!!!!!!!!!!!!! THE MODULE THAT IMPLEMENTS CALFUN !!!!!!!!!!!!!!!!!!!
module calfun_mod

implicit none
private
public :: calfun

contains

    subroutine calfun (x, f)
    ! The Chebyquad test problem (Fletcher, 1965)
    implicit none

    real(kind(0.0D0)), intent(in) :: x(:)
    real(kind(0.0D0)), intent(out) :: f
    real(kind(0.0D0)) :: y(size(x) + 1, size(x) + 1), tmp
    integer :: i, n

    n = size(x)

    y(1 : n, 1) = 1.0D0
    y(1 : n, 2) = 2.0D0 * x - 1.0D0
    do i = 2, n
        y(1: n, i + 1) = 2.0D0 * y(1 : n, 2)*y(1 : n, i) - y(1 : n, i - 1)
    end do

    f = 0.0D0
    do i = 1, n + 1
        tmp = sum(y(1 : n, i))/real(n, kind(0.0D0))
        if (mod(i, 2) /= 0) then
            tmp = tmp + 1.0D0 / real(i * i - 2 * i, kind(0.0D0))
        end if
        f = f + tmp * tmp
    end do
    end subroutine calfun

end module calfun_mod


!!!!!!!!!!!!!!!!!!!!!!!!!!! THE MAIN PROGRAM !!!!!!!!!!!!!!!!!!!!!!!!!!!
program newuoa_exmp

! The following line makes NEWUOA available.
!----------------------------------------------------------------------!
use newuoa_mod, only : newuoa
!----------------------------------------------------------------------!

! The following line specifies which module provides CALFUN.
! If CALFUN is provided by an external subroutine instead of a module, 
! then remove this line and uncomment the "external calfun" line below.
!----------------------------------------------------------------------!
use calfun_mod, only : calfun
!----------------------------------------------------------------------!

implicit none

integer :: i, n, alloc_stat
real(kind(0.0D0)) :: rhobeg, f
real(kind(0.0D0)), allocatable :: x(:)

! If CALFUN is provided as an external subroutine, then remove the line
! of "use calfun_mod, only : calfun", and uncomment the following line:
!----------------------------------------------------------------------!
!external calfun
!----------------------------------------------------------------------!

do n = 2, 10, 2
    ! Sets up the initial X for the Chebyquad problem.
    if (allocated(x)) deallocate(x)
    allocate(x(n), stat = alloc_stat)
    if (alloc_stat /= 0) print *, 'Memory allocation failed.'
    do i = 1, n
        x(i) = real(i, kind(0.0D0))/real(n + 1, kind(0.0D0))
    end do

    rhobeg = 0.2D0 * x(1)

    print '(/1A, I2)', 'Result with N = ', n

    ! The following line illustrates how to call NEWUOA.
    !------------------------------------------------------------------!
    call newuoa(calfun, x, f, rhobeg = rhobeg, iprint = 2)
    !------------------------------------------------------------------!
    ! In additon to the required arguments CALFUN, X, and F, the above
    ! illustration specifies also RHOBEG and IPRINT, which are optional.
    ! All the unspecified optional arguments (RHOEND, MAXFUN, etc.) will
    ! take their default values coded in NEWUOA. You can also ignore all
    ! the optional arguments and invoke NEWUOA by the following line.
    !------------------------------------------------------------------!
    ! call newuoa(calfun, x, f)
    !------------------------------------------------------------------!
end do

end program newuoa_exmp
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by rudrab** [comment]
Hi, thanks for the details. You are right that the line 
`  au BufWritePre <buffer> silent! :%s/\v(\w|\)) ?(\:\:) ?(\w|-)/\1\2 \3/g      " `::`
`
changes `integer :: i` to `integer:: i`, which is mostly personal preference (just like we don't put space before `,`, but after it). 
That is actually why I asked your vimrc config. If you use `let fortran_linter=2`, then it will use `fprettify` or you can set `fortran_linter=3` to disable linting al together.

**Comment by zaikunzhang** [comment]
Thank you @rudrab for the explanation. I see. I will try fprepttify. Again, thank you for this plugin. I code in Fortran a lot using Vim, and I hope I found vimf90 much earlier!

**Comment by rudrab** [comment]
I am very glad that you find vimf90 helpful.
