### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by certik** [rudrab/vimf90#13]
If possible, you should add a license to the repository.

Thanks for this! I am a Vim and Fortran user!

**Comment by rudrab** [comment]
Dear @certik Thanks for your comment. Its great pleasure for me that the creator of lfortran is showing interest in this project.
I have added `gplv3` license file to the project. Most of the files already has a license text already.

Please suggest me improvements.

**Comment by certik** [comment]
Perfect, thank you! You are right, the files already had copyright, I missed that. I think it's always good to have the LICENSE file, that way it is clear. Thanks for adding it.
