### ISSUE TITLE
Can't use the compile functions

### ISSUE THREAD

**Issue by fedebenelli** [rudrab/vimf90#14]
I'm unable to use the compile functions, like `fortran_compile` or `fortran_run`, either by trying `<leader>cr` or `:fotran_run`. Not sure how could I debug it

**Comment by rudrab** [comment]
@fedebenelli Do you mean that `<leader>cr` is running but giving error in compilation or it is not trigarring the command at all?

**Comment by rudrab** [comment]
If it is not mapping at all, can you please check your `:map` output, which function is leading to `call Run()`? With my present setup,it is `\\cr`.

**Comment by fedebenelli** [comment]
`map` gives:
`\,cr        * : call Run()<CR>`, running with that it works. Thanks for the tip! 
Is the `\` hardcoded? my current leader key is just `,`

**Comment by rudrab** [comment]
@fedebenelli yes for now it seems to be hardcoded (unintentionally, as an effect of personal habit). I will change that soon (may be by this weekend).
Thanks for reporting this.

**Comment by fedebenelli** [comment]
@rudrab allright! Thanks for the quick answer, and for the plugin too! It's saving me a lot of time and making the use of Fortran far more friendly!

**Comment by rudrab** [comment]
Corrected and updated. Please check.
