### ISSUE TITLE
Problem with fortran block

### ISSUE THREAD

**Issue by soumyajyotih** [rudrab/vimf90#5]
I am getting this error when I am trying to open any fortran 90 file. 
~/.vim/bundle/vimf90/ftplugin/fortran_block.vim: 
E117: Unknown function: provider#python#Call

**Comment by rudrab** [comment]
Please let me know your python3 version. :)

**Comment by soumyajyotih** [comment]
I am using neovim NVIM v0.2.3-dev and python3 is Python 3.6.3

**Comment by soumyajyotih** [comment]
Fixed it for neovim. pip3 install --upgrade neovim and then re install neovim from apt repo. But vim8 in ubuntu 17.10 gives other problems, although it is compiled with python3 support. 
line   26:
E319: Sorry, the command is not available in this version: python << EOF
line   27:
E492: Not an editor command: import re
line   28:
E492: Not an editor command: import vim
line   30:
E492: Not an editor command: class SyntaxElement:
line   31:
E492: Not an editor command:     def __init__(self, pattern, closingline):
line   32:
E492: Not an editor command:         self.pattern = pattern
line   33:
E492: Not an editor command:         self.closingline = closingline
line   34:
E492: Not an editor command:     def match(self, line): 
line   36:
E488: Trailing characters:         match = self.pattern.search(line)
line   37:
E121: Undefined variable: match
E15: Invalid expression: match:
line   60:
E133: :return not inside a function
line   62:
E133: :return not inside a function
line  107:
E171: Missing :endif

**Comment by soumyajyotih** [comment]
Problem fixed with source compilation of vim8.
