### ISSUE TITLE
Plugin Initialization related with python3 using Vundle installation

### ISSUE THREAD

**Issue by robinzyb** [rudrab/vimf90#6]
Hi, 
    I got a issue when I install plugin by Vundle method. Here is the errors

```
Error detected while processing /Users/robinzhuang/.vim/bundle/vimf90/ftplugin/fortran_block.vim:
line   26:
E319: Sorry, the command is not available in this version: python3 << EOF
line   27:
E492: Not an editor command: import re
line   28:
E492: Not an editor command: import vim
line   30:
E492: Not an editor command: class SyntaxElement:
line   31:
E492: Not an editor command:     def __init__(self, pattern, closingline):
line   32:
E492: Not an editor command:         self.pattern = pattern
line   33:
E492: Not an editor command:         self.closingline = closingline
line   34:
E492: Not an editor command:     def match(self, line): 
line   36:
E488: Trailing characters:         match = self.pattern.search(line)
line   37:
E121: Undefined variable: match
line   60:
E133: :return not inside a function
line   62:
E133: :return not inside a function
line  107:
E171: Missing :endif
```

**Comment by rudrab** [comment]
Hi,
Thanks for reporting. Please reinstall it (`plugin update` should do). If it still does not work, kindly let me know you vim version and if it is compiled with `python3` i.e. the output of 
vim --version |grep Improved
vim --version |grep python3

But, I guess reinstall will work.
Kindly let me know if it doesn't

**Comment by robinzyb** [comment]
Hi, 
 thank you for quick reply.
 I tried update and some error is shown.
The result of 
```
vim --version |grep Improved 
(no output)
vim --version |grep python3
+cmdline_info      +libcall           -python3           +visualextra
```
what dose this mean?  Not familiar with vim, by the way I'm using the macOS Catalina

**Comment by robinzyb** [comment]
I see the point of this problem, 
My vim version is not Improved one and not compiled with python3
I reinstall my vim using the newest `brew install vim`
this question is solved.
Thanks for you help
I will close this question

**Comment by rudrab** [comment]
Thanks a lot. 
Please consider "star" the project. 
Also please let me know about other features you would like to see.
