### ISSUE TITLE
Disable fprettify

### ISSUE THREAD

**Issue by impresionista** [rudrab/vimf90#8]
Hi, I'm not sure how to disable fprettify at saving and I don't want to have it messing with my own indentation criteria (I know that they might not be the ideal ones, but they are useful to me). 
I've look for the config option in the docs but couldn't find it. It's available?

Thanks! :)

**Comment by rudrab** [comment]
Hi, Thanks for this. `fprettify` is not enabled by default.  you probably has enabled it using `let fortran_linter = 2` If you dont want it, just use `let fortran_linter = -1`. 

Check [here](https://github.com/rudrab/vimf90#linting).

**Comment by rudrab** [comment]
Please let me know if that is working.

**Comment by impresionista** [comment]
> Hi, Thanks for this. `fprettify` is not enabled by default. you probably has enabled it using `let fortran_linter = 2` If you dont want it, just use `let fortran_linter = -1`.

Oh! Sorry about that. Now I understand it better (It's really clear in the docs, I misunderstood it).
I have linter enabled because I wanted some corrections in spaces, but force indenting was really messing my codes.
I've tried passing some options to `fprettify` but none worked as I intended. Here are the options I tried, just in case:

`let g:fprettify_options = '--disable-indent --disable-whitespace'`
`let g:fprettify_options = '-i 2 --disable-indent --disable-whitespace'`
`let g:fprettify_options = '-i 0 --disable-indent --disable-whitespace'`

> 
> Check [here](https://github.com/rudrab/vimf90#linting).

**Comment by impresionista** [comment]
> Please let me know if that is working.

Its working perfectly with your suggestion. Thanks!! :)

**Comment by rudrab** [comment]
Great to know its working for you. 
While a single person is writing the code and the doc, there may be some gray area. If you kindly take some time to let me know where you had problem, I will try to explain it more elaborately.

**Comment by impresionista** [comment]
> Great to know its working for you.
> While a single person is writing the code and the doc, there may be some gray area. If you kindly take some time to let me know where you had problem, I will try to explain it more elaborately.

Yes, of course! It's a great pluggin and it's really well documented, I misinterpreted the docs.

Anyway, I'll try to explain the issue.
When I open some code with nvim with `let fortran_linter = 2` and `let g:fprettify_options = ''` options in .vimrc the indentation gets messed up. Here is an example code. 

Original: https://pastebin.com/qndgfxiw
Modified: https://pastebin.com/GNNEMv4Z

- _Lines 8 to 23:_ Got indented by 3 spaces.
- _After line 26:_ Everithing get indexed from 2 spaces to 3 spaces.
- _Lines 117, 118 and 119:_ Gets 'unindexed' (this is not weird, it's consequent with fortran style guides). 

I'm not so sure why 3 spaces tho, because fortran style says indexing must be done with 2 spaces.

I hope this could be useful. Please tell me if I could be useful in any way!

P.S.: All my fortran codes are available in my GitLab page.

**Comment by pseewald** [comment]
@impresionista 3 spaces is the fprettify default that you can customize to whatever you want with the `-i` option (see `fprettify --help`).

@rudrab Vim already provides a formatting option `gq` so for a better integration of fprettify into Vim workflows I recommend to integrate fprettify by `autocmd Filetype fortran setlocal formatprg=fprettify\ --silent`. Then you can leave it up to the user whether fprettify should be invoked manually or whether it should happen automatically.

**Comment by rudrab** [comment]
@pseewald 
Thanks for your comment, 
This is what exactly done, with   `au BufWritePre <buffer> :execute 'silent %!fprettify ' . g:fprettify_options`  inside `ftplugin`.

**Comment by impresionista** [comment]
> @impresionista 3 spaces is the fprettify default that you can customize to whatever you want with the `-i` option (see `fprettify --help`).

Thanks! I've tried with `-i` option before and mannaged to have 2 spaces (or none unsing 0).

> @rudrab Vim already provides a formatting option `gq` so for a better integration of fprettify into Vim workflows I recommend to integrate fprettify by `autocmd Filetype fortran setlocal formatprg=fprettify\ --silent`. Then you can leave it up to the user whether fprettify should be invoked manually or whether it should happen automatically.


Anyhow, now that I understand a little more about fpretiffy I think I prefer to have it disabled with `let fortran_linter = -1`.
Is there a way to have automatic code fixing disabled and only have linter flags for errors?

**Comment by pseewald** [comment]
> @pseewald
> Thanks for your comment,
> This is what exactly done, with `au BufWritePre <buffer> :execute 'silent %!fprettify ' . g:fprettify_options` inside `ftplugin`.

Yes but if I understand correctly, this automatically applies fprettify before write? My point is that most users will disable it since they may not like enforced autoformatting, or they don't care about customizing fprettify according to their coding convention. On the other hand with `gq` fprettify can be applied selectively as needed and also there is no need to disable it in any case (very useful for refactoring etc.). Even if enforced reformatting is an option, you should still bind fprettify to `gq` for those who prefer to invoke fprettify in the "Vim way".

**Comment by rudrab** [comment]
@pseewald fprettify is enabled only when user enable it by `fortran_linter=2`, not by default. If user is not using this, he has to `gg-gq` manually.  I am putting it here , because, I dont think user will have fprettify installed.

**Comment by rudrab** [comment]
> Is there a way to have automatic code fixing disabled and only have linter flags for errors?

@impresionista  for linting only, you should look at `ALE`.  So, if you have any problem, kindly open a new thread(good for future reference).

**Comment by impresionista** [comment]
Ok! Thanks for the advice!

**Comment by rudrab** [comment]
> Yes, of course! It's a great pluggin and it's really well documented, I misinterpreted the docs.

I have updated the plugin and documentation. Kindly have a look.
