### ISSUE TITLE
Disable startup question to install python dependencies

### ISSUE THREAD

**Issue by Carltoffel** [rudrab/vimf90#9]
If I don't want to use at least one out of `fprettify`, `fortls` and `unidecode` I get an annoying message every time the plugin loads. It would be nice if there was another way besides installing these modules.

**Comment by rudrab** [comment]
Thanks for reporting. It was not intended to load every time, and I understand the frustration. I will check it and update soon.

Thanks.

**Comment by rudrab** [comment]
Hi, update is pushed. 
Please add `let fortran_dep_install=3` in vimrc.

Kindly let me know if this solves your problem.

**Comment by Carltoffel** [comment]
Hi, thank you for this very fast response and fix. It does work, but the yes/no/dont-ask choice seems to be a little bit unfinished. If I understand the code correctly you are currently only doing something if the choice is 'yes' but you ignore the other two. If you don't plan to do something if the 'don't ask again' option is chosen, I would simply remove this 3rd option. However, the hint under the question to simply set this value in vimrc is very nice!

**Comment by Carltoffel** [comment]
btw: did you hear about https://fortran-lang.org and https://fortran-lang.discourse.group ? There we want to (re-) unite the Fortran community to revive Fortran. If you want to take part in this, feel free to check this out! :)

**Comment by rudrab** [comment]
> btw: did you hear about https://fortran-lang.org and https://fortran-lang.discourse.group ? There we want to (re-) unite the Fortran community to revive Fortran. If you want to take part in this, feel free to check this out! :)

Wow. Thats a nice piece of information. I was not aware of them. I was stuck to `comp.lang.fortran` google group. I will defenitely join that.

**Comment by rudrab** [comment]
> Hi, thank you for this very fast response and fix. It does work, but the yes/no/dont-ask choice seems to be a little bit unfinished. If I understand the code correctly you are currently only doing something if the choice is 'yes' but you ignore the other two. If you don't plan to do something if the 'don't ask again' option is chosen, I would simply remove this 3rd option. However, the hint under the question to simply set this value in vimrc is very nice!

You are absolutely correct. When I put the 3rd option "Dont ask me again", I was thinking of inserting that to vimrc automatically. But that is too much a job that can simply done by giving the info to the user. So, I have dropped the idea. I will remove the option.
